### ISSUE TITLE
When you enter a number in the numpad, the "display" changes dimension

### ISSUE THREAD

**Issue by bobboteck** [bobboteck/easy-numpad#3]
I noticed that when you enter a number in the numpad, the "display" changes slightly larger than when it is empty. If you find it, I open another issue.

I merged the pull request!!

_Originally posted by @bobboteck in https://github.com/bobboteck/easy-numpad/issues/1#issuecomment-488759500_

**Comment by bobboteck** [comment]
Also the Roboto font is not always available, aggiungere un font alternativo

**Comment by bobboteck** [comment]
> Also the Roboto font is not always available, aggiungere un font alternativo

Added a default font as from origin with [commit](https://github.com/bobboteck/easy-numpad/commit/9855da5f5b05d133eb4ac6889373a00d3e01f7ab)

**Comment by SergioSubrizi** [comment]
solved changing the easy-numpad.css, - .easy-numpad-output - setting the font to 50px instead of 56px

**Comment by bobboteck** [comment]
Closed with #4
