### ISSUE TITLE
Numbers with no digits after the decimal point are not correctly interpreted

### ISSUE THREAD

**Issue by amontefusco** [bobboteck/easy-numpad#5]
Pressing

 1 2 . Done

results in an empty field (instead of 12 as expected).

(Test made on the example web gui).

**Comment by bobboteck** [comment]
the problem is clear, it depends on the fact that the input field is numeric, so the number entered is not validated (12.)

![image](https://user-images.githubusercontent.com/5130571/57176644-8e003100-6e5a-11e9-8e18-0b2fd5d28169.png)

**Comment by bobboteck** [comment]
Added the resolution of this bug in the [project](https://github.com/bobboteck/easy-numpad/projects/1)

**Comment by amontefusco** [comment]
Should be enough to change the 
```
\.\d+ 
```
in 
```
\.(\d+)?
```

Moreover, in general, one would expect that the previuos correct value was left  untouched.

**Comment by bobboteck** [comment]
validation is managed by the browser, for now I manage the problem simply by removing the point if it is the last character
